language: go
go:
- '1.11'
- 'tip'
matrix:
  fast_finish: true
  allowed_failures:
  - go: 'tip'
env:
  GO111MODULE: "on"
before_install:
  - export PATH=$PATH:$PWD/adr-tools/src
  - git clone https://github.com/npryce/adr-tools
install: go mod download
script: make ci
